Update structures.py
adds 4k requested data fields caused by this error

ERROR : ombi : TypeError has occurred : <lambda>() got an unexpected keyword argument 'is4kRequest' while creating OmbiMovieRequest structure for movie. data attempted is: